/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schedule;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author waa
 */


public class Add_Employee extends javax.swing.JFrame {

    /**
     * Creates new form Add_Employee
     */
    public Add_Employee() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        first_label = new javax.swing.JLabel();
        last_label = new javax.swing.JLabel();
        first_field = new javax.swing.JTextField();
        last_field = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        add_employee = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mondaystart = new javax.swing.JComboBox<>();
        mondayfinish = new javax.swing.JComboBox<>();
        tuesdayfinish = new javax.swing.JComboBox<>();
        wednesdayfinish = new javax.swing.JComboBox<>();
        fridayfinish = new javax.swing.JComboBox<>();
        saturdayfinish = new javax.swing.JComboBox<>();
        sundayfinish = new javax.swing.JComboBox<>();
        thursdayfinish = new javax.swing.JComboBox<>();
        wednesdaystart = new javax.swing.JComboBox<>();
        thursdaystart = new javax.swing.JComboBox<>();
        tuesdaystart = new javax.swing.JComboBox<>();
        fridaystart = new javax.swing.JComboBox<>();
        saturdaystart = new javax.swing.JComboBox<>();
        sundaystart = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        email_label = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        name_label.setText("Name");

        first_label.setText("First");

        last_label.setText("Last");

        first_field.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                first_fieldPropertyChange(evt);
            }
        });

        last_field.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                last_fieldPropertyChange(evt);
            }
        });
        last_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                last_fieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(name_label)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(first_label)
                    .addComponent(first_field, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(last_label)
                    .addComponent(last_field, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_label)
                    .addComponent(last_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_field, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_field, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add_employee.setText("Add Employee");
        add_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_employeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(add_employee)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_employee)
                .addContainerGap())
        );

        jLabel4.setText("Monday");

        jLabel5.setText("Tuesday");

        jLabel6.setText("Wednesday");

        jLabel7.setText("Friday");

        jLabel8.setText("Saturday");

        jLabel9.setText("Thursday");

        jLabel10.setText("Sunday");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        jLabel12.setText("Start");

        jLabel13.setText("Finish");

        mondaystart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        mondaystart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondaystartActionPerformed(evt);
            }
        });

        mondayfinish.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        mondayfinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayfinishActionPerformed(evt);
            }
        });

        tuesdayfinish.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        tuesdayfinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayfinishActionPerformed(evt);
            }
        });

        wednesdayfinish.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        wednesdayfinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayfinishActionPerformed(evt);
            }
        });

        fridayfinish.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        fridayfinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayfinishActionPerformed(evt);
            }
        });

        saturdayfinish.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        saturdayfinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdayfinishActionPerformed(evt);
            }
        });

        sundayfinish.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        sundayfinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundayfinishActionPerformed(evt);
            }
        });

        thursdayfinish.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        thursdayfinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayfinishActionPerformed(evt);
            }
        });

        wednesdaystart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        wednesdaystart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdaystartActionPerformed(evt);
            }
        });

        thursdaystart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        thursdaystart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdaystartActionPerformed(evt);
            }
        });

        tuesdaystart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        tuesdaystart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdaystartActionPerformed(evt);
            }
        });

        fridaystart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        fridaystart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridaystartActionPerformed(evt);
            }
        });

        saturdaystart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        saturdaystart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturdaystartActionPerformed(evt);
            }
        });

        sundaystart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A" ,  "12 am", "1 am","2 am","3 am","4 am","5 am","6 am","7 am","8 am","9 am","10 am","11 am",
            "12 pm" ,"1 pm","2 pm","3 pm","4 pm","5 pm","6 pm","7 pm","8 pm","9 pm","10 pm","11 pm"

        }));
        sundaystart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sundaystartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(185, 185, 185)
                                            .addComponent(jLabel12)
                                            .addGap(37, 37, 37))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tuesdaystart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(mondaystart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(wednesdaystart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(thursdaystart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fridaystart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(saturdaystart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(sundaystart, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(6, 6, 6))))
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(1, 1, 1)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fridayfinish, 0, 97, Short.MAX_VALUE)
                                    .addComponent(thursdayfinish, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sundayfinish, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mondayfinish, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tuesdayfinish, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(wednesdayfinish, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saturdayfinish, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(wednesdayfinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(thursdayfinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thursdaystart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fridayfinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fridaystart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(saturdaystart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saturdayfinish)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(mondayfinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tuesdayfinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(mondaystart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tuesdaystart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wednesdaystart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sundaystart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sundayfinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        email_label.setText("Email");

        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_field)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(email_label)
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(email_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_employeeActionPerformed
        // TODO add your handling code here:
        if("".equals(first_field.getText( )))
        {
            JOptionPane.showMessageDialog(this, "Enter first name ");
        }
        else if("".equals(last_field.getText( )))
        {
            JOptionPane.showMessageDialog(this, "Enter last name ");

        }        
        
         else if(mondaystart.getSelectedIndex() > mondayfinish.getSelectedIndex()    )
        {
            JOptionPane.showMessageDialog(this, "Invalid times chosen for Monday");

        }
         else if(tuesdaystart.getSelectedIndex() > tuesdayfinish.getSelectedIndex()    )
        {
            JOptionPane.showMessageDialog(this, "Invalid times chosen for Tuesday");

        }
        else if(wednesdaystart.getSelectedIndex() > wednesdayfinish.getSelectedIndex()    )
        {
            JOptionPane.showMessageDialog(this, "Invalid times chosen for Wednesday");

        }      
        
        else if(thursdaystart.getSelectedIndex() > thursdayfinish.getSelectedIndex()    )
        {
            JOptionPane.showMessageDialog(this, "Invalid times chosen for Thursday");

        }
        else if(fridaystart.getSelectedIndex() > fridayfinish.getSelectedIndex()    )
        {
            JOptionPane.showMessageDialog(this, "Invalid times chosen for Friday");

        }           
        else if(saturdaystart.getSelectedIndex() > saturdayfinish.getSelectedIndex()    )
        {
            JOptionPane.showMessageDialog(this, "Invalid times chosen for Saturday");

        }
        else if(sundaystart.getSelectedIndex() > sundayfinish.getSelectedIndex()    )
        {
            JOptionPane.showMessageDialog(this, "Invalid times chosen for Sunday");

        }          
        
        else
        {
            Employees en1 = new Employees();
            en1.setFirstName(first_field.getText());
            en1.setLastName(last_field.getText());
            if(!"".equals(email_field.getText()))
            {
                en1.setEmail(email_field.getText());
            }    
            
            if(mondaystart.getSelectedIndex() >0 )
            {
                en1.setMondayStart(mondaystart.getSelectedIndex() -1);
                en1.setMondayFinish(mondayfinish.getSelectedIndex() -1);
                
            }
            if(tuesdaystart.getSelectedIndex() >0 )
            {
                en1.setTuesdayStart(tuesdaystart.getSelectedIndex() -1);
                en1.setTuesdayFinish(tuesdayfinish.getSelectedIndex() -1);
                
            }  
             if(wednesdaystart.getSelectedIndex() >0 )
            {
                en1.setWednesdayStart(wednesdaystart.getSelectedIndex() -1);
                en1.setWednesdayFinish(wednesdayfinish.getSelectedIndex() -1);
                
            }
            if(thursdaystart.getSelectedIndex() >0 )
            {
                en1.setThursdayStart(thursdaystart.getSelectedIndex() -1);
                en1.setThursdayFinish(thursdayfinish.getSelectedIndex() -1);
                
            }     
            if(fridaystart.getSelectedIndex() >0 )
            {
                en1.setFridayStart(fridaystart.getSelectedIndex() -1);
                en1.setFridayFinish(fridayfinish.getSelectedIndex() -1);
                
            }
             if(saturdaystart.getSelectedIndex() >0 )
            {
                en1.setSaturdayStart(saturdaystart.getSelectedIndex() -1);
                en1.setSaturdayFinish(saturdayfinish.getSelectedIndex() -1);
                
            }
            if(sundaystart.getSelectedIndex() >0 )
            {
                en1.setSundayStart(sundaystart.getSelectedIndex() -1);
                en1.setSundayFinish(sundayfinish.getSelectedIndex() -1);
                
            }          
            EntityManagerFactory creator = Persistence.createEntityManagerFactory("SchedulePU");
            EmployeesJpaController called = new EmployeesJpaController(creator);
            try {
                called.create(en1);
            } catch (Exception ex) {
                Logger.getLogger(Add_Employee.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                    
        }        
        
        
    }//GEN-LAST:event_add_employeeActionPerformed

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void last_fieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_last_fieldPropertyChange
        // TODO add your handling code here:
        /*if(last_field.getText().equals("") && first_field.getText().equals("") )
        {
            mondaystart.setEnabled(false);
        }    
        else
        {
             mondaystart.setEnabled(true);
        }    
        */
    }//GEN-LAST:event_last_fieldPropertyChange

    private void first_fieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_first_fieldPropertyChange
        // TODO add your handling code here:
      /*  if(last_field.getText().equals("") && first_field.getText().equals("") )
        {
            mondaystart.setEnabled(false);
        }    
        else
        {
             mondaystart.setEnabled(true);
        }   
        */
    }//GEN-LAST:event_first_fieldPropertyChange

    private void last_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_last_fieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_last_fieldKeyTyped

    private void mondaystartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondaystartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondaystartActionPerformed

    private void tuesdayfinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayfinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesdayfinishActionPerformed

    private void mondayfinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayfinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondayfinishActionPerformed

    private void wednesdayfinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayfinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayfinishActionPerformed

    private void fridayfinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayfinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fridayfinishActionPerformed

    private void saturdayfinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdayfinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturdayfinishActionPerformed

    private void sundayfinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundayfinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sundayfinishActionPerformed

    private void thursdayfinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayfinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursdayfinishActionPerformed

    private void wednesdaystartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdaystartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdaystartActionPerformed

    private void thursdaystartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdaystartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursdaystartActionPerformed

    private void tuesdaystartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdaystartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesdaystartActionPerformed

    private void fridaystartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridaystartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fridaystartActionPerformed

    private void saturdaystartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturdaystartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturdaystartActionPerformed

    private void sundaystartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sundaystartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sundaystartActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_employee;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField first_field;
    private javax.swing.JLabel first_label;
    private javax.swing.JComboBox<String> fridayfinish;
    private javax.swing.JComboBox<String> fridaystart;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField last_field;
    private javax.swing.JLabel last_label;
    private javax.swing.JComboBox<String> mondayfinish;
    private javax.swing.JComboBox<String> mondaystart;
    private javax.swing.JLabel name_label;
    private javax.swing.JComboBox<String> saturdayfinish;
    private javax.swing.JComboBox<String> saturdaystart;
    private javax.swing.JComboBox<String> sundayfinish;
    private javax.swing.JComboBox<String> sundaystart;
    private javax.swing.JComboBox<String> thursdayfinish;
    private javax.swing.JComboBox<String> thursdaystart;
    private javax.swing.JComboBox<String> tuesdayfinish;
    private javax.swing.JComboBox<String> tuesdaystart;
    private javax.swing.JComboBox<String> wednesdayfinish;
    private javax.swing.JComboBox<String> wednesdaystart;
    // End of variables declaration//GEN-END:variables
}
