/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schedule;
import java.util.Hashtable;
import javax.persistence.EntityManagerFactory;
import javax.swing.JLabel;
import javax.persistence.Persistence;
/**
 *
 * @author waa
 */
public class add_employee_frame extends javax.swing.JDialog {

    /**
     * Creates new form add_employee_frame
     */
    
    Hashtable table_time = new Hashtable(); 
    
    public add_employee_frame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    add_employee_frame() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        monday_label = new javax.swing.JButton();
        monday_slider = new slider.RangeSlider();
        tuesday_slider = new slider.RangeSlider();
        tuesday_label = new javax.swing.JButton();
        wednesday_slider = new slider.RangeSlider();
        wednesday_label = new javax.swing.JButton();
        thursday_slider = new slider.RangeSlider();
        thursday_label = new javax.swing.JButton();
        friday_slider = new slider.RangeSlider();
        friday_label = new javax.swing.JButton();
        saturday_slider = new slider.RangeSlider();
        saturday_label = new javax.swing.JButton();
        sunday_slider = new slider.RangeSlider();
        sunday_label = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        add_employee_done_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        last_name_input = new javax.swing.JTextField();
        first_name_input = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setToolTipText("");

        monday_label.setText("Monday");

        monday_slider.setMajorTickSpacing(1);
        table_time.put(new Integer(0), new JLabel("12am"));
        table_time.put(new Integer(1), new JLabel("1am"));
        table_time.put(new Integer(2), new JLabel("2am"));
        table_time.put(new Integer(3), new JLabel("3am"));
        table_time.put(new Integer(4), new JLabel("4am"));
        table_time.put(new Integer(5), new JLabel("5am"));
        table_time.put(new Integer(6), new JLabel("6am"));
        table_time.put(new Integer(7), new JLabel("7am"));
        table_time.put(new Integer(8), new JLabel("8am"));
        table_time.put(new Integer(9), new JLabel("9am"));
        table_time.put(new Integer(10), new JLabel("10am"));
        table_time.put(new Integer(11), new JLabel("11am"));
        table_time.put(new Integer(12), new JLabel("12pm"));
        table_time.put(new Integer(13), new JLabel("1pm"));
        table_time.put(new Integer(14), new JLabel("2pm"));
        table_time.put(new Integer(15), new JLabel("3pm"));
        table_time.put(new Integer(16), new JLabel("4pm"));
        table_time.put(new Integer(17), new JLabel("5pm"));
        table_time.put(new Integer(18), new JLabel("6pm"));
        table_time.put(new Integer(19), new JLabel("7pm"));
        table_time.put(new Integer(20), new JLabel("8pm"));
        table_time.put(new Integer(21), new JLabel("9pm"));
        table_time.put(new Integer(22), new JLabel("10pm"));
        table_time.put(new Integer(23), new JLabel("11pm"));
        monday_slider.setLabelTable(table_time);
        monday_slider.setPaintLabels(true);
        monday_slider.setMaximum(24);
        monday_slider.setMinorTickSpacing(1);
        monday_slider.setPaintTicks(true);
        monday_slider.setSnapToTicks(true);
        monday_slider.setToolTipText("");
        monday_slider.setValue(8);
        monday_slider.setInheritsPopupMenu(true);
        monday_slider.setName(""); // NOI18N
        monday_slider.setUpperValue(16);
        monday_slider.setValueIsAdjusting(true);
        monday_slider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                monday_sliderPropertyChange(evt);
            }
        });

        tuesday_slider.setMajorTickSpacing(1);
        tuesday_slider.setMaximum(24);
        tuesday_slider.setMinorTickSpacing(1);
        table_time.put(new Integer(0), new JLabel("12am"));
        table_time.put(new Integer(1), new JLabel("1am"));
        table_time.put(new Integer(2), new JLabel("2am"));
        table_time.put(new Integer(3), new JLabel("3am"));
        table_time.put(new Integer(4), new JLabel("4am"));
        table_time.put(new Integer(5), new JLabel("5am"));
        table_time.put(new Integer(6), new JLabel("6am"));
        table_time.put(new Integer(7), new JLabel("7am"));
        table_time.put(new Integer(8), new JLabel("8am"));
        table_time.put(new Integer(9), new JLabel("9am"));
        table_time.put(new Integer(10), new JLabel("10am"));
        table_time.put(new Integer(11), new JLabel("11am"));
        table_time.put(new Integer(12), new JLabel("12pm"));
        table_time.put(new Integer(13), new JLabel("1pm"));
        table_time.put(new Integer(14), new JLabel("2pm"));
        table_time.put(new Integer(15), new JLabel("3pm"));
        table_time.put(new Integer(16), new JLabel("4pm"));
        table_time.put(new Integer(17), new JLabel("5pm"));
        table_time.put(new Integer(18), new JLabel("6pm"));
        table_time.put(new Integer(19), new JLabel("7pm"));
        table_time.put(new Integer(20), new JLabel("8pm"));
        table_time.put(new Integer(21), new JLabel("9pm"));
        table_time.put(new Integer(22), new JLabel("10pm"));
        table_time.put(new Integer(23), new JLabel("11pm"));
        tuesday_slider.setLabelTable(table_time);
        tuesday_slider.setPaintLabels(true);
        tuesday_slider.setPaintTicks(true);
        tuesday_slider.setSnapToTicks(true);
        tuesday_slider.setToolTipText("");
        tuesday_slider.setValue(8);
        tuesday_slider.setInheritsPopupMenu(true);
        tuesday_slider.setName(""); // NOI18N
        tuesday_slider.setUpperValue(16);
        tuesday_slider.setValueIsAdjusting(true);
        tuesday_slider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tuesday_sliderPropertyChange(evt);
            }
        });

        tuesday_label.setText("Tuesday");

        wednesday_slider.setMajorTickSpacing(1);
        wednesday_slider.setMaximum(24);
        wednesday_slider.setMinorTickSpacing(1);
        table_time.put(new Integer(0), new JLabel("12am"));
        table_time.put(new Integer(1), new JLabel("1am"));
        table_time.put(new Integer(2), new JLabel("2am"));
        table_time.put(new Integer(3), new JLabel("3am"));
        table_time.put(new Integer(4), new JLabel("4am"));
        table_time.put(new Integer(5), new JLabel("5am"));
        table_time.put(new Integer(6), new JLabel("6am"));
        table_time.put(new Integer(7), new JLabel("7am"));
        table_time.put(new Integer(8), new JLabel("8am"));
        table_time.put(new Integer(9), new JLabel("9am"));
        table_time.put(new Integer(10), new JLabel("10am"));
        table_time.put(new Integer(11), new JLabel("11am"));
        table_time.put(new Integer(12), new JLabel("12pm"));
        table_time.put(new Integer(13), new JLabel("1pm"));
        table_time.put(new Integer(14), new JLabel("2pm"));
        table_time.put(new Integer(15), new JLabel("3pm"));
        table_time.put(new Integer(16), new JLabel("4pm"));
        table_time.put(new Integer(17), new JLabel("5pm"));
        table_time.put(new Integer(18), new JLabel("6pm"));
        table_time.put(new Integer(19), new JLabel("7pm"));
        table_time.put(new Integer(20), new JLabel("8pm"));
        table_time.put(new Integer(21), new JLabel("9pm"));
        table_time.put(new Integer(22), new JLabel("10pm"));
        table_time.put(new Integer(23), new JLabel("11pm"));
        wednesday_slider.setLabelTable(table_time);
        wednesday_slider.setPaintLabels(true);
        wednesday_slider.setPaintTicks(true);
        wednesday_slider.setSnapToTicks(true);
        wednesday_slider.setToolTipText("");
        wednesday_slider.setValue(8);
        wednesday_slider.setInheritsPopupMenu(true);
        wednesday_slider.setName(""); // NOI18N
        wednesday_slider.setUpperValue(16);
        wednesday_slider.setValueIsAdjusting(true);
        wednesday_slider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                wednesday_sliderPropertyChange(evt);
            }
        });

        wednesday_label.setText("Wednesday");

        thursday_slider.setMajorTickSpacing(1);
        thursday_slider.setMaximum(24);
        thursday_slider.setMinorTickSpacing(1);
        thursday_slider.setLabelTable(table_time);
        thursday_slider.setPaintLabels(true);
        thursday_slider.setPaintTicks(true);
        thursday_slider.setSnapToTicks(true);
        thursday_slider.setToolTipText("");
        thursday_slider.setValue(8);
        thursday_slider.setInheritsPopupMenu(true);
        thursday_slider.setName(""); // NOI18N
        thursday_slider.setUpperValue(16);
        thursday_slider.setValueIsAdjusting(true);
        thursday_slider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                thursday_sliderPropertyChange(evt);
            }
        });

        thursday_label.setText("Thursday");

        friday_slider.setMajorTickSpacing(1);
        friday_slider.setMaximum(24);
        friday_slider.setLabelTable(table_time);
        friday_slider.setPaintLabels(true);
        friday_slider.setMinorTickSpacing(1);
        friday_slider.setPaintTicks(true);
        friday_slider.setSnapToTicks(true);
        friday_slider.setToolTipText("");
        friday_slider.setValue(8);
        friday_slider.setInheritsPopupMenu(true);
        friday_slider.setName(""); // NOI18N
        friday_slider.setUpperValue(16);
        friday_slider.setValueIsAdjusting(true);
        friday_slider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                friday_sliderPropertyChange(evt);
            }
        });

        friday_label.setText("Friday");

        saturday_slider.setMajorTickSpacing(1);
        saturday_slider.setMaximum(24);
        saturday_slider.setLabelTable(table_time);
        saturday_slider.setPaintLabels(true);
        saturday_slider.setMinorTickSpacing(1);
        saturday_slider.setPaintTicks(true);
        saturday_slider.setSnapToTicks(true);
        saturday_slider.setToolTipText("");
        saturday_slider.setValue(8);
        saturday_slider.setInheritsPopupMenu(true);
        saturday_slider.setName(""); // NOI18N
        saturday_slider.setUpperValue(16);
        saturday_slider.setValueIsAdjusting(true);
        saturday_slider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                saturday_sliderPropertyChange(evt);
            }
        });

        saturday_label.setText("Saturday");

        sunday_slider.setMajorTickSpacing(1);
        sunday_slider.setMaximum(24);
        sunday_slider.setMinorTickSpacing(1);
        sunday_slider.setLabelTable(table_time);
        sunday_slider.setPaintLabels(true);
        sunday_slider.setPaintTicks(true);
        sunday_slider.setSnapToTicks(true);
        sunday_slider.setToolTipText("");
        sunday_slider.setValue(8);
        sunday_slider.setInheritsPopupMenu(true);
        sunday_slider.setName(""); // NOI18N
        sunday_slider.setUpperValue(16);
        sunday_slider.setValueIsAdjusting(true);
        sunday_slider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sunday_sliderPropertyChange(evt);
            }
        });

        sunday_label.setText("Sunday");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(monday_label, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(wednesday_label)
                                .addComponent(tuesday_label)
                                .addComponent(thursday_label)
                                .addComponent(friday_label))
                            .addGap(2, 2, 2)))
                    .addComponent(saturday_label)
                    .addComponent(sunday_label))
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(friday_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thursday_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturday_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sunday_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wednesday_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monday_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuesday_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {friday_label, monday_label, saturday_label, sunday_label, thursday_label, tuesday_label, wednesday_label});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monday_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monday_label, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tuesday_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tuesday_label, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(wednesday_label))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wednesday_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thursday_label, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(thursday_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(friday_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(friday_label, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saturday_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(saturday_label)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sunday_slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sunday_label, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {friday_label, monday_label, saturday_label, sunday_label, sunday_slider, thursday_label, tuesday_label, wednesday_label});

        add_employee_done_button.setText("Done");
        add_employee_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_employee_done_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setText("Last");

        jLabel3.setText("First");

        jLabel1.setText("Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(last_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(103, Short.MAX_VALUE)
                    .addComponent(first_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(last_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(first_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setText("Email");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(email_input, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_employee_done_button)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_employee_done_button)
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(58, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sunday_sliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sunday_sliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sunday_sliderPropertyChange

    private void saturday_sliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_saturday_sliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_saturday_sliderPropertyChange

    private void friday_sliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_friday_sliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_friday_sliderPropertyChange

    private void thursday_sliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_thursday_sliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_thursday_sliderPropertyChange

    private void wednesday_sliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_wednesday_sliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesday_sliderPropertyChange

    private void tuesday_sliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tuesday_sliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesday_sliderPropertyChange

    private void monday_sliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_monday_sliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_monday_sliderPropertyChange

    private void add_employee_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_employee_done_buttonActionPerformed
        // TODO add your handling code here:
       // if
         Employees en1 = new Employees();
            en1.setFirstName(first_name_input.getText());
            en1.setLastName(last_name_input.getText());
            en1.setEmployeeName(first_name_input.getText()  + " " + last_name_input.getText());
             EntityManagerFactory creator = Persistence.createEntityManagerFactory("schedulePU");
            EmployeesJpaController called = new EmployeesJpaController(creator);
            called.create(en1);
           // main a = new main();
            
        
    }//GEN-LAST:event_add_employee_done_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_employee_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_employee_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_employee_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_employee_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
              
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                add_employee_frame dialog = new add_employee_frame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_employee_done_button;
    private javax.swing.JTextField email_input;
    private javax.swing.JTextField first_name_input;
    private javax.swing.JButton friday_label;
    private slider.RangeSlider friday_slider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField last_name_input;
    private javax.swing.JButton monday_label;
    private slider.RangeSlider monday_slider;
    private javax.swing.JButton saturday_label;
    private slider.RangeSlider saturday_slider;
    private javax.swing.JButton sunday_label;
    private slider.RangeSlider sunday_slider;
    private javax.swing.JButton thursday_label;
    private slider.RangeSlider thursday_slider;
    private javax.swing.JButton tuesday_label;
    private slider.RangeSlider tuesday_slider;
    private javax.swing.JButton wednesday_label;
    private slider.RangeSlider wednesday_slider;
    // End of variables declaration//GEN-END:variables
}
