/**
 * This file was generated by the JPA Modeler
 */
package schedule;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * @author waa
 */
@Entity
@Table(name = "EMPLOYEES")
@NamedQueries({
    @NamedQuery(name = "Employees.findAll", query = "SELECT e FROM Employees e"),
    @NamedQuery(name = "Employees.findById", query = "SELECT e FROM Employees e WHERE e.id = :id"),
    @NamedQuery(name = "Employees.findByFirstName", query = "SELECT e FROM Employees e WHERE e.firstName = :firstName"),
    @NamedQuery(name = "Employees.findByLastName", query = "SELECT e FROM Employees e WHERE e.lastName = :lastName"),
    @NamedQuery(name = "Employees.findByEmployeeName", query = "SELECT e FROM Employees e WHERE e.employeeName = :employeeName"),
    @NamedQuery(name = "Employees.findByMondayStart", query = "SELECT e FROM Employees e WHERE e.mondayStart = :mondayStart"),
    @NamedQuery(name = "Employees.findByMondayFinish", query = "SELECT e FROM Employees e WHERE e.mondayFinish = :mondayFinish"),
    @NamedQuery(name = "Employees.findByTuesdayStart", query = "SELECT e FROM Employees e WHERE e.tuesdayStart = :tuesdayStart"),
    @NamedQuery(name = "Employees.findByTuesdayFinish", query = "SELECT e FROM Employees e WHERE e.tuesdayFinish = :tuesdayFinish"),
    @NamedQuery(name = "Employees.findByWednesdayStart", query = "SELECT e FROM Employees e WHERE e.wednesdayStart = :wednesdayStart"),
    @NamedQuery(name = "Employees.findByWednesdayFinish", query = "SELECT e FROM Employees e WHERE e.wednesdayFinish = :wednesdayFinish"),
    @NamedQuery(name = "Employees.findByThursdayStart", query = "SELECT e FROM Employees e WHERE e.thursdayStart = :thursdayStart"),
    @NamedQuery(name = "Employees.findByThursdayFinish", query = "SELECT e FROM Employees e WHERE e.thursdayFinish = :thursdayFinish"),
    @NamedQuery(name = "Employees.findByFridayStart", query = "SELECT e FROM Employees e WHERE e.fridayStart = :fridayStart"),
    @NamedQuery(name = "Employees.findByFridayFinish", query = "SELECT e FROM Employees e WHERE e.fridayFinish = :fridayFinish"),
    @NamedQuery(name = "Employees.findBySaturdayStart", query = "SELECT e FROM Employees e WHERE e.saturdayStart = :saturdayStart"),
    @NamedQuery(name = "Employees.findBySaturdayFinish", query = "SELECT e FROM Employees e WHERE e.saturdayFinish = :saturdayFinish"),
    @NamedQuery(name = "Employees.findBySundayStart", query = "SELECT e FROM Employees e WHERE e.sundayStart = :sundayStart"),
    @NamedQuery(name = "Employees.findBySundayFinish", query = "SELECT e FROM Employees e WHERE e.sundayFinish = :sundayFinish")})
public class Employees implements Serializable {

    @Transient
    private PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);

    @Column(name = "ID")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "FIRST_NAME")
    @Basic
    private String firstName;

    @Column(name = "LAST_NAME")
    @Basic
    private String lastName;

    @Column(name = "EMPLOYEE_NAME")
    @Basic
    private String employeeName;

    @Column(name = "PASSWORD")
    @Lob
    @Basic
    private String password;

    @Column(name = "EMAIL")
    @Lob
    @Basic
    private String email;

    @Column(name = "MONDAY_START")
    @Basic
    private Integer mondayStart;

    @Column(name = "MONDAY_FINISH")
    @Basic
    private Integer mondayFinish;

    @Column(name = "TUESDAY_START")
    @Basic
    private Integer tuesdayStart;

    @Column(name = "TUESDAY_FINISH")
    @Basic
    private Integer tuesdayFinish;

    @Column(name = "WEDNESDAY_START")
    @Basic
    private Integer wednesdayStart;

    @Column(name = "WEDNESDAY_FINISH")
    @Basic
    private Integer wednesdayFinish;

    @Column(name = "THURSDAY_START")
    @Basic
    private Integer thursdayStart;

    @Column(name = "THURSDAY_FINISH")
    @Basic
    private Integer thursdayFinish;

    @Column(name = "FRIDAY_START")
    @Basic
    private Integer fridayStart;

    @Column(name = "FRIDAY_FINISH")
    @Basic
    private Integer fridayFinish;

    @Column(name = "SATURDAY_START")
    @Basic
    private Integer saturdayStart;

    @Column(name = "SATURDAY_FINISH")
    @Basic
    private Integer saturdayFinish;

    @Column(name = "SUNDAY_START")
    @Basic
    private Integer sundayStart;

    @Column(name = "SUNDAY_FINISH")
    @Basic
    private Integer sundayFinish;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        Integer oldId = this.id;
        this.id = id;
        changeSupport.firePropertyChange("id", oldId, id);
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        String oldFirstName = this.firstName;
        this.firstName = firstName;
        changeSupport.firePropertyChange("firstName", oldFirstName, firstName);
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        String oldLastName = this.lastName;
        this.lastName = lastName;
        changeSupport.firePropertyChange("lastName", oldLastName, lastName);
    }

    public String getEmployeeName() {
        return this.employeeName;
    }

    public void setEmployeeName(String employeeName) {
        String oldEmployeeName = this.employeeName;
        this.employeeName = employeeName;
        changeSupport.firePropertyChange("employeeName", oldEmployeeName, employeeName);
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        String oldPassword = this.password;
        this.password = password;
        changeSupport.firePropertyChange("password", oldPassword, password);
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        String oldEmail = this.email;
        this.email = email;
        changeSupport.firePropertyChange("email", oldEmail, email);
    }

    public Integer getMondayStart() {
        return this.mondayStart;
    }

    public void setMondayStart(Integer mondayStart) {
        Integer oldMondayStart = this.mondayStart;
        this.mondayStart = mondayStart;
        changeSupport.firePropertyChange("mondayStart", oldMondayStart, mondayStart);
    }

    public Integer getMondayFinish() {
        return this.mondayFinish;
    }

    public void setMondayFinish(Integer mondayFinish) {
        Integer oldMondayFinish = this.mondayFinish;
        this.mondayFinish = mondayFinish;
        changeSupport.firePropertyChange("mondayFinish", oldMondayFinish, mondayFinish);
    }

    public Integer getTuesdayStart() {
        return this.tuesdayStart;
    }

    public void setTuesdayStart(Integer tuesdayStart) {
        Integer oldTuesdayStart = this.tuesdayStart;
        this.tuesdayStart = tuesdayStart;
        changeSupport.firePropertyChange("tuesdayStart", oldTuesdayStart, tuesdayStart);
    }

    public Integer getTuesdayFinish() {
        return this.tuesdayFinish;
    }

    public void setTuesdayFinish(Integer tuesdayFinish) {
        Integer oldTuesdayFinish = this.tuesdayFinish;
        this.tuesdayFinish = tuesdayFinish;
        changeSupport.firePropertyChange("tuesdayFinish", oldTuesdayFinish, tuesdayFinish);
    }

    public Integer getWednesdayStart() {
        return this.wednesdayStart;
    }

    public void setWednesdayStart(Integer wednesdayStart) {
        Integer oldWednesdayStart = this.wednesdayStart;
        this.wednesdayStart = wednesdayStart;
        changeSupport.firePropertyChange("wednesdayStart", oldWednesdayStart, wednesdayStart);
    }

    public Integer getWednesdayFinish() {
        return this.wednesdayFinish;
    }

    public void setWednesdayFinish(Integer wednesdayFinish) {
        Integer oldWednesdayFinish = this.wednesdayFinish;
        this.wednesdayFinish = wednesdayFinish;
        changeSupport.firePropertyChange("wednesdayFinish", oldWednesdayFinish, wednesdayFinish);
    }

    public Integer getThursdayStart() {
        return this.thursdayStart;
    }

    public void setThursdayStart(Integer thursdayStart) {
        Integer oldThursdayStart = this.thursdayStart;
        this.thursdayStart = thursdayStart;
        changeSupport.firePropertyChange("thursdayStart", oldThursdayStart, thursdayStart);
    }

    public Integer getThursdayFinish() {
        return this.thursdayFinish;
    }

    public void setThursdayFinish(Integer thursdayFinish) {
        Integer oldThursdayFinish = this.thursdayFinish;
        this.thursdayFinish = thursdayFinish;
        changeSupport.firePropertyChange("thursdayFinish", oldThursdayFinish, thursdayFinish);
    }

    public Integer getFridayStart() {
        return this.fridayStart;
    }

    public void setFridayStart(Integer fridayStart) {
        Integer oldFridayStart = this.fridayStart;
        this.fridayStart = fridayStart;
        changeSupport.firePropertyChange("fridayStart", oldFridayStart, fridayStart);
    }

    public Integer getFridayFinish() {
        return this.fridayFinish;
    }

    public void setFridayFinish(Integer fridayFinish) {
        Integer oldFridayFinish = this.fridayFinish;
        this.fridayFinish = fridayFinish;
        changeSupport.firePropertyChange("fridayFinish", oldFridayFinish, fridayFinish);
    }

    public Integer getSaturdayStart() {
        return this.saturdayStart;
    }

    public void setSaturdayStart(Integer saturdayStart) {
        Integer oldSaturdayStart = this.saturdayStart;
        this.saturdayStart = saturdayStart;
        changeSupport.firePropertyChange("saturdayStart", oldSaturdayStart, saturdayStart);
    }

    public Integer getSaturdayFinish() {
        return this.saturdayFinish;
    }

    public void setSaturdayFinish(Integer saturdayFinish) {
        Integer oldSaturdayFinish = this.saturdayFinish;
        this.saturdayFinish = saturdayFinish;
        changeSupport.firePropertyChange("saturdayFinish", oldSaturdayFinish, saturdayFinish);
    }

    public Integer getSundayStart() {
        return this.sundayStart;
    }

    public void setSundayStart(Integer sundayStart) {
        Integer oldSundayStart = this.sundayStart;
        this.sundayStart = sundayStart;
        changeSupport.firePropertyChange("sundayStart", oldSundayStart, sundayStart);
    }

    public Integer getSundayFinish() {
        return this.sundayFinish;
    }

    public void setSundayFinish(Integer sundayFinish) {
        Integer oldSundayFinish = this.sundayFinish;
        this.sundayFinish = sundayFinish;
        changeSupport.firePropertyChange("sundayFinish", oldSundayFinish, sundayFinish);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }

}
